config/routes.rb
Napdea::Application.routes.draw do
  resources :signups

  root "signups#new"

  

end

app/models/signup.rb
class Signup < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  before_action :set_signup, only: [:show, :edit, :update, :destroy]

  # GET /signups
  # GET /signups.json
  def index
    @signups = Signup.all
  end

  # GET /signups/1
  # GET /signups/1.json
  def show
  end

  # GET /signups/new
  def new
    @signup = Signup.new
  end

  # GET /signups/1/edit
  def edit
  end

  # POST /signups
  # POST /signups.json
  def create
    @signup = Signup.new(signup_params)

    respond_to do |format|
      if @signup.save
        format.html { redirect_to @signup, notice: 'Signup was successfully created.' }
        format.json { render action: 'show', status: :created, location: @signup }
      else
        format.html { render action: 'new' }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /signups/1
  # PATCH/PUT /signups/1.json
  def update
    respond_to do |format|
      if @signup.update(signup_params)
        format.html { redirect_to @signup, notice: 'Signup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signups/1
  # DELETE /signups/1.json
  def destroy
    @signup.destroy
    respond_to do |format|
      format.html { redirect_to signups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_signup
      @signup = Signup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def signup_params
      params.require(:signup).permit(:email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Napdea</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/signups/_form.html.haml
= form_for @signup do |f|
  - if @signup.errors.any?
    #error_explanation
      %h2= "#{pluralize(@signup.errors.count, "error")} prohibited this signup from being saved:"
      %ul
        - @signup.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/views/signups/edit.html.haml
%h1 Editing signup

= render 'form'

= link_to 'Show', @signup
\|
= link_to 'Back', signups_path

app/views/signups/index.html.haml
%h1 Listing signups

%table
  %tr
    %th Email
    %th
    %th
    %th

  - @signups.each do |signup|
    %tr
      %td= signup.email
      %td= link_to 'Show', signup
      %td= link_to 'Edit', edit_signup_path(signup)
      %td= link_to 'Destroy', signup, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Signup', new_signup_path

app/views/signups/new.html.haml
%h1 New signup

= render 'form'

= link_to 'Back', signups_path

app/views/signups/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @signup.email

= link_to 'Edit', edit_signup_path(@signup)
\|
= link_to 'Back', signups_path